# Generated by Django 2.2.4 on 2019-08-18 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('device_lat', models.FloatField(blank=True, null=True)),
                ('device_long', models.FloatField(blank=True, null=True)),
                ('tempureture', models.CharField(blank=True, max_length=255, null=True)),
                ('humudity', models.IntegerField(blank=True, null=True)),
                ('pressure', models.CharField(blank=True, max_length=255, null=True)),
                ('time_s', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notfication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('Nolu cihaz açıldı', ' Nolu cihaz açıldı'), ('Nolu cihazı açmağa cəhd göstərildi', 'Nolu cihazı açmağa cəhd göstərildi')], max_length=50)),
                ('time_s', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Device')),
            ],
            options={
                'verbose_name': 'Info Notfication',
                'verbose_name_plural': 'Info Notifications',
            },
        ),
    ]
