# Generated by Django 2.2.4 on 2019-08-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notfication',
            name='notification_type',
            field=models.CharField(choices=[('Nolu_cihaz_açıldı', ' Nolu cihaz açıldı'), ('Nolu_cihazı_açmağa_cəhd_göstərildi', 'Nolu cihazı açmağa cəhd göstərildi')], max_length=50),
        ),
    ]
