# Generated by Django 2.2.4 on 2019-08-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_device_by_who'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='by_who',
        ),
        migrations.AddField(
            model_name='notfication',
            name='by_who',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
